{
  "openapi": "3.0.1",
  "servers": [
    {
      "url": "http://localhost:8080/api",
      "description": "localhost"
    },
    {
      "url": "https://play.dhis2.org/{version}/api",
      "description": "DHIS2 demo server",
      "variables": {
        "version": {
          "description": "DHIS 2 release version",
          "default": "2.28",
          "enum": [
            "2.26",
            "2.27",
            "2.28",
            "dev"
          ]
        }
      }
    }
  ],
  "info": {
    "description": " The Web API is a component which makes it possible for external systems to access and manipulate data stored in an instance of DHIS2. More precisely, it provides a programmatic interface to a wide range of exposed data and service methods for applications such as third-party software clients, web portals and internal DHIS2 modules.\n# The Web API adheres to many of the principles behind the REST architectural style. To mention some few and important ones\n- The fundamental building blocks are referred to as *resources*. A resource can be anything exposed to the Web, from a document to a business process - anything a client might want to interact with. The information aspects of a resource can be retrieved or exchanged through resource representations. A representation is a view of a resource's state at any given time. For instance, the *reportTable* resource in DHIS2 represents a tabular report of aggregated data for a certain set of parameters. This resource can be retrieved in a variety of representation formats including HTML, PDF, and MS Excel.\n- All resources can be uniquely identified by a URI (also referred to a/s URL). All resources have a default representation. You can indicate that you are interested in a specific representation by supplying an Accept HTTP header, a file extension or a format query parameter. So in order to retrieve the PDF representation of a report table you can supply an ***Accept: application/pdf*** header or append ***.pdf*** or ***?format=pdf*** to your request URL.\n- Interactions with the API requires correct use of HTTP methods or verbs. This implies that for a resource you must issue a GET request when you want to retrieve it, POST request when you want to create one, PUT when you want to update it and DELETE when you want to remove it. So if you want to retrieve the default representation of a report table you can send a GET request to e.g. */reportTable/iu8j/hYgF6t*, where the last part is the report table identifier.\n- Resource representations are linkable, meaning that representations advertise other resources which are relevant to the current one by embedding links into itself (please be aware that you need to request href in your field filter to have this working. This feature greatly improves the usability and robustness of the API. For instance, you can easily navigate to the indicators which are associated with a report table from the reportTable resource through the embedded links using your preferred representation format. ",
    "version": "2.29",
    "title": "DHIS 2 API",
    "termsOfService": "",
    "contact": {
      "email": "dev@dhis2.org"
    }
  },
  "tags": [],
  "paths": {
    "/constants": {
      "post": {
        "summary": "add a new constant definition",
        "description": "",
        "parameters": [],
        "operationId": "",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "name": {
                    "type": "string",
                    "maxLength": 230
                  },
                  "value": {
                    "type": "string",
                    "format": "double"
                  },
                  "description": {
                    "type": "string",
                    "maxLength": 2147483647
                  },
                  "shortName": {
                    "type": "string",
                    "maxLength": 50
                  },
                  "code": {
                    "type": "string",
                    "maxLength": 50
                  },
                  "uid": {
                    "type": "string",
                    "maxLength": 11
                  }
                },
                "required": [
                  "name"
                ],
                "description": "Constants are static values which can be made available to users for use in data elements and indicators. Some indicators, such as \"Couple year protection rate\" depend on constants which usually do not change over time.",
                "example": {
                  "name": "newConstant",
                  "value": "123.456",
                  "shortName": "nConst",
                  "displayName": "nConst for display - ta da",
                  "description": "a simple example of a constant",
                  "code": "QWERTY12345",
                  "uid": "bCqvfPR02Im"
                }
              }
            }
          }
        },
        "responses": {
          "default": {
            "description": "Default response"
          }
        }
      },
      "put": {
        "summary": "update a constant definition",
        "description": "",
        "parameters": [],
        "operationId": "",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "name": {
                    "type": "string",
                    "maxLength": 230
                  },
                  "value": {
                    "type": "string",
                    "format": "double"
                  },
                  "description": {
                    "type": "string",
                    "maxLength": 2147483647
                  },
                  "shortName": {
                    "type": "string",
                    "maxLength": 50
                  },
                  "code": {
                    "type": "string",
                    "maxLength": 50
                  },
                  "uid": {
                    "type": "string",
                    "maxLength": 11
                  }
                },
                "required": [
                  "name"
                ],
                "description": "Constants are static values which can be made available to users for use in data elements and indicators. Some indicators, such as \"Couple year protection rate\" depend on constants which usually do not change over time.",
                "example": {
                  "name": "newConstant",
                  "value": "123.456",
                  "shortName": "nConst",
                  "displayName": "nConst for display - ta da",
                  "description": "a simple example of a constant",
                  "code": "QWERTY12345",
                  "uid": "bCqvfPR02Im"
                }
              }
            }
          }
        },
        "responses": {
          "default": {
            "description": "Default response"
          }
        }
      },
      "get": {
        "summary": "get constants based on an applied filter",
        "description": "",
        "parameters": [
          {
            "name": "fields",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "Fields to be returned by the query",
            "example": ":all"
          }
        ],
        "operationId": "",
        "responses": {
          "default": {
            "description": "Default response"
          }
        }
      }
    },
    "/constants/{uid}": {
      "get": {
        "summary": "get details of a constant based on it's unique ID",
        "parameters": [
          {
            "in": "path",
            "name": "uid",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "bCqvfPR02Im"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "name": {
                      "type": "string",
                      "maxLength": 230
                    },
                    "value": {
                      "type": "string",
                      "format": "double"
                    },
                    "description": {
                      "type": "string",
                      "maxLength": 2147483647
                    },
                    "shortName": {
                      "type": "string",
                      "maxLength": 50
                    },
                    "code": {
                      "type": "string",
                      "maxLength": 50
                    },
                    "uid": {
                      "type": "string",
                      "maxLength": 11
                    }
                  },
                  "required": [
                    "name"
                  ],
                  "description": "Constants are static values which can be made available to users for use in data elements and indicators. Some indicators, such as \"Couple year protection rate\" depend on constants which usually do not change over time.",
                  "example": {
                    "name": "newConstant",
                    "value": "123.456",
                    "shortName": "nConst",
                    "displayName": "nConst for display - ta da",
                    "description": "a simple example of a constant",
                    "code": "QWERTY12345",
                    "uid": "bCqvfPR02Im"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "delete a  constant based on it's unique ID",
        "parameters": [
          {
            "in": "path",
            "name": "uid",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "bCqvfPR02Im"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "name": {
                      "type": "string",
                      "maxLength": 230
                    },
                    "value": {
                      "type": "string",
                      "format": "double"
                    },
                    "description": {
                      "type": "string",
                      "maxLength": 2147483647
                    },
                    "shortName": {
                      "type": "string",
                      "maxLength": 50
                    },
                    "code": {
                      "type": "string",
                      "maxLength": 50
                    },
                    "uid": {
                      "type": "string",
                      "maxLength": 11
                    }
                  },
                  "required": [
                    "name"
                  ],
                  "description": "Constants are static values which can be made available to users for use in data elements and indicators. Some indicators, such as \"Couple year protection rate\" depend on constants which usually do not change over time.",
                  "example": {
                    "name": "newConstant",
                    "value": "123.456",
                    "shortName": "nConst",
                    "displayName": "nConst for display - ta da",
                    "description": "a simple example of a constant",
                    "code": "QWERTY12345",
                    "uid": "bCqvfPR02Im"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "externalDocs": {
    "description": "",
    "url": "https://www.dhis2.org/documentation"
  },
  "components": {
    "schemas": {
      "Constant": {
        "properties": {
          "name": {
            "type": "string",
            "maxLength": 230
          },
          "value": {
            "type": "string",
            "format": "double"
          },
          "description": {
            "type": "string",
            "maxLength": 2147483647
          },
          "shortName": {
            "type": "string",
            "maxLength": 50
          },
          "code": {
            "type": "string",
            "maxLength": 50
          },
          "uid": {
            "type": "string",
            "maxLength": 11
          }
        },
        "required": [
          "name"
        ],
        "description": "Constants are static values which can be made available to users for use in data elements and indicators. Some indicators, such as \"Couple year protection rate\" depend on constants which usually do not change over time.",
        "example": {
          "name": "newConstant",
          "value": "123.456",
          "shortName": "nConst",
          "displayName": "nConst for display - ta da",
          "description": "a simple example of a constant",
          "code": "QWERTY12345",
          "uid": "bCqvfPR02Im"
        }
      }
    },
    "requestBodies": {},
    "securitySchemes": {
      "basicAuth": {
        "type": "http",
        "scheme": "basic"
      },
      "oAuth": {
        "type": "openIdConnect",
        "openIdConnectUrl": "https://play.dhis2.org/api/oAuthClients"
      }
    },
    "links": {},
    "callbacks": {}
  },
  "security": [
    {
      "basicAuth": []
    },
    {
      "oAuth": []
    }
  ]
}
